name: rekrutmentpolri
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  get: 4.6.5
  carousel_slider: ^4.2.1
  flutter_native_splash: ^2.2.16
  intl: ^0.17.0
  lottie: 1.4.1
  flutter_svg: 1.1.3
  firebase_core_platform_interface: 4.5.1
  url_launcher: 6.1.5
  firebase_core: ^1.24.0
  google_sign_in: ^5.4.4
  firebase_auth: ^3.11.2
  image_picker: ^0.8.5+3
  firebase_storage: ^10.3.11
  cloud_firestore: ^3.5.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/image/
    - assets/
  uses-material-design: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/image/11.png

flutter_icons:
  android: launcher_icon
  image_path: assets/image/logo.png
  ios: true
